//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODAMobile.AppResources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KamooniHost.AppResources.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 DAYS.
        /// </summary>
        public static string button_2_days {
            get {
                return ResourceManager.GetString("button_2_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 DAYS.
        /// </summary>
        public static string button_3_days {
            get {
                return ResourceManager.GetString("button_3_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation.
        /// </summary>
        public static string button_accommodation {
            get {
                return ResourceManager.GetString("button_accommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string button_activity {
            get {
                return ResourceManager.GetString("button_activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD EXTRAS.
        /// </summary>
        public static string button_add_extras {
            get {
                return ResourceManager.GetString("button_add_extras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD NEW SERVER.
        /// </summary>
        public static string button_add_new_server {
            get {
                return ResourceManager.GetString("button_add_new_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD SERVER.
        /// </summary>
        public static string button_add_server {
            get {
                return ResourceManager.GetString("button_add_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD TO BILL.
        /// </summary>
        public static string button_add_to_bill {
            get {
                return ResourceManager.GetString("button_add_to_bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHECK IN.
        /// </summary>
        public static string button_check_in {
            get {
                return ResourceManager.GetString("button_check_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHECK OUT.
        /// </summary>
        public static string button_check_out {
            get {
                return ResourceManager.GetString("button_check_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIRM.
        /// </summary>
        public static string button_confirm {
            get {
                return ResourceManager.GetString("button_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIRM CHECK-IN.
        /// </summary>
        public static string button_confirm_check_in {
            get {
                return ResourceManager.GetString("button_confirm_check_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIRM NO-SHOW.
        /// </summary>
        public static string button_confirm_no_show {
            get {
                return ResourceManager.GetString("button_confirm_no_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIRM PAYMENT.
        /// </summary>
        public static string button_confirm_payment {
            get {
                return ResourceManager.GetString("button_confirm_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE BOOKING.
        /// </summary>
        public static string button_create_booking {
            get {
                return ResourceManager.GetString("button_create_booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAST WEEK.
        /// </summary>
        public static string button_last_week {
            get {
                return ResourceManager.GetString("button_last_week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        public static string button_login {
            get {
                return ResourceManager.GetString("button_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAY ALL.
        /// </summary>
        public static string button_pay_all {
            get {
                return ResourceManager.GetString("button_pay_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAY AND CHECKOUT.
        /// </summary>
        public static string button_pay_and_checkout {
            get {
                return ResourceManager.GetString("button_pay_and_checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAY NOW.
        /// </summary>
        public static string button_pay_now {
            get {
                return ResourceManager.GetString("button_pay_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROCEED.
        /// </summary>
        public static string button_proceed {
            get {
                return ResourceManager.GetString("button_proceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string button_profile {
            get {
                return ResourceManager.GetString("button_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCAN.
        /// </summary>
        public static string button_scan {
            get {
                return ResourceManager.GetString("button_scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT.
        /// </summary>
        public static string button_select {
            get {
                return ResourceManager.GetString("button_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string button_select_country {
            get {
                return ResourceManager.GetString("button_select_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NATIONALITY.
        /// </summary>
        public static string button_select_nationality {
            get {
                return ResourceManager.GetString("button_select_nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string button_select_province {
            get {
                return ResourceManager.GetString("button_select_province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROOM.
        /// </summary>
        public static string button_select_room {
            get {
                return ResourceManager.GetString("button_select_room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN UP.
        /// </summary>
        public static string button_sign_up {
            get {
                return ResourceManager.GetString("button_sign_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBMIT.
        /// </summary>
        public static string button_submit {
            get {
                return ResourceManager.GetString("button_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBMIT DETAILS.
        /// </summary>
        public static string button_submit_details {
            get {
                return ResourceManager.GetString("button_submit_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THIS WEEK.
        /// </summary>
        public static string button_this_week {
            get {
                return ResourceManager.GetString("button_this_week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOMORROW.
        /// </summary>
        public static string button_tomorrow {
            get {
                return ResourceManager.GetString("button_tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport.
        /// </summary>
        public static string button_transport {
            get {
                return ResourceManager.GetString("button_transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string button_update {
            get {
                return ResourceManager.GetString("button_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Profile.
        /// </summary>
        public static string button_update_profile {
            get {
                return ResourceManager.GetString("button_update_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIEW BILLS.
        /// </summary>
        public static string button_view_bills {
            get {
                return ResourceManager.GetString("button_view_bills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Profile.
        /// </summary>
        public static string button_view_profile {
            get {
                return ResourceManager.GetString("button_view_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Booking.
        /// </summary>
        public static string clickable_add_booking {
            get {
                return ResourceManager.GetString("clickable_add_booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string clickable_forgot_password {
            get {
                return ResourceManager.GetString("clickable_forgot_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan to Login.
        /// </summary>
        public static string clickable_scan_to_login {
            get {
                return ResourceManager.GetString("clickable_scan_to_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select another server.
        /// </summary>
        public static string clickable_select_another_server {
            get {
                return ResourceManager.GetString("clickable_select_another_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string clickable_sign_up {
            get {
                return ResourceManager.GetString("clickable_sign_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no expected arrivals for this day.
        /// </summary>
        public static string content_checkin_done_early {
            get {
                return ResourceManager.GetString("content_checkin_done_early", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no pending no-shows for this week.
        /// </summary>
        public static string content_checkin_done_no_shows {
            get {
                return ResourceManager.GetString("content_checkin_done_no_shows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no expected arrivals for today.
        /// </summary>
        public static string content_checkin_done_today {
            get {
                return ResourceManager.GetString("content_checkin_done_today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string content_delete {
            get {
                return ResourceManager.GetString("content_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DETAILS SAVED.
        /// </summary>
        public static string content_details_saved {
            get {
                return ResourceManager.GetString("content_details_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dont have an account?.
        /// </summary>
        public static string content_dont_have_an_account {
            get {
                return ResourceManager.GetString("content_dont_have_an_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your server URL.
        /// </summary>
        public static string content_enter_server_url {
            get {
                return ResourceManager.GetString("content_enter_server_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading….
        /// </summary>
        public static string content_loading {
            get {
                return ResourceManager.GetString("content_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no extras added.
        /// </summary>
        public static string content_no_extras {
            get {
                return ResourceManager.GetString("content_no_extras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no extras to add.
        /// </summary>
        public static string content_no_extras_to_add {
            get {
                return ResourceManager.GetString("content_no_extras_to_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no open bookings.
        /// </summary>
        public static string content_no_open_bookings {
            get {
                return ResourceManager.GetString("content_no_open_bookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no payments made yet.
        /// </summary>
        public static string content_no_past_payments {
            get {
                return ResourceManager.GetString("content_no_past_payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All outstanding payments paid.
        /// </summary>
        public static string content_no_payments {
            get {
                return ResourceManager.GetString("content_no_payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No room available.
        /// </summary>
        public static string content_no_rooms_available {
            get {
                return ResourceManager.GetString("content_no_rooms_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Category.
        /// </summary>
        public static string content_select_category {
            get {
                return ResourceManager.GetString("content_select_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Guest.
        /// </summary>
        public static string content_select_guest {
            get {
                return ResourceManager.GetString("content_select_guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the number of guests.
        /// </summary>
        public static string content_select_guests {
            get {
                return ResourceManager.GetString("content_select_guests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please take the time to verify that your information is correct and populate all the empty fields.
        /// </summary>
        public static string content_verification_description {
            get {
                return ResourceManager.GetString("content_verification_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User or Password can&apos;t be empty.
        /// </summary>
        public static string dialog_message_acc_empty {
            get {
                return ResourceManager.GetString("dialog_message_acc_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-In Confirmed.
        /// </summary>
        public static string dialog_message_check_in_confirmed {
            get {
                return ResourceManager.GetString("dialog_message_check_in_confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-In Failed.
        /// </summary>
        public static string dialog_message_check_in_failed {
            get {
                return ResourceManager.GetString("dialog_message_check_in_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email link sent to property email.\nPlease set your password at this link.\n\n After this is done, you can log in.
        /// </summary>
        public static string dialog_message_host_selected {
            get {
                return ResourceManager.GetString("dialog_message_host_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to log out?.
        /// </summary>
        public static string dialog_message_logout {
            get {
                return ResourceManager.GetString("dialog_message_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internet connection is required.\nPlease check your internet settings..
        /// </summary>
        public static string dialog_message_no_internet {
            get {
                return ResourceManager.GetString("dialog_message_no_internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rooms available!.
        /// </summary>
        public static string dialog_message_no_rooms_available {
            get {
                return ResourceManager.GetString("dialog_message_no_rooms_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No room found. Please recheck the room availability..
        /// </summary>
        public static string dialog_message_room_availability {
            get {
                return ResourceManager.GetString("dialog_message_room_availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No room available on your selected date.
        /// </summary>
        public static string dialog_message_room_availability_date {
            get {
                return ResourceManager.GetString("dialog_message_room_availability_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room booked successfully.
        /// </summary>
        public static string dialog_message_room_booking {
            get {
                return ResourceManager.GetString("dialog_message_room_booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have.
        /// </summary>
        public static string dialog_message_saved_details_1 {
            get {
                return ResourceManager.GetString("dialog_message_saved_details_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pending submissions.
        /// </summary>
        public static string dialog_message_saved_details_2 {
            get {
                return ResourceManager.GetString("dialog_message_saved_details_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pending submission.
        /// </summary>
        public static string dialog_message_saved_details_3 {
            get {
                return ResourceManager.GetString("dialog_message_saved_details_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server error. Try again later in 1 minute..
        /// </summary>
        public static string dialog_message_server_error {
            get {
                return ResourceManager.GetString("dialog_message_server_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-In.
        /// </summary>
        public static string dialog_title_check_in {
            get {
                return ResourceManager.GetString("dialog_title_check_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string dialog_title_forgot_password {
            get {
                return ResourceManager.GetString("dialog_title_forgot_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string dialog_title_login {
            get {
                return ResourceManager.GetString("dialog_title_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string dialog_title_logout {
            get {
                return ResourceManager.GetString("dialog_title_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Connection.
        /// </summary>
        public static string dialog_title_no_internet {
            get {
                return ResourceManager.GetString("dialog_title_no_internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Availability.
        /// </summary>
        public static string dialog_title_room_availability {
            get {
                return ResourceManager.GetString("dialog_title_room_availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking.
        /// </summary>
        public static string dialog_title_room_booking {
            get {
                return ResourceManager.GetString("dialog_title_room_booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Details.
        /// </summary>
        public static string dialog_title_saved_details {
            get {
                return ResourceManager.GetString("dialog_title_saved_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Room.
        /// </summary>
        public static string dialog_title_select_room {
            get {
                return ResourceManager.GetString("dialog_title_select_room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string dialog_title_sign_up {
            get {
                return ResourceManager.GetString("dialog_title_sign_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification.
        /// </summary>
        public static string dialog_title_verification {
            get {
                return ResourceManager.GetString("dialog_title_verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently Selected Server.
        /// </summary>
        public static string heading_currently_selected_server {
            get {
                return ResourceManager.GetString("heading_currently_selected_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string heading_dialog_nationality {
            get {
                return ResourceManager.GetString("heading_dialog_nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Payment.
        /// </summary>
        public static string heading_dialog_register_payment {
            get {
                return ResourceManager.GetString("heading_dialog_register_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Payer.
        /// </summary>
        public static string heading_dialog_select_payer {
            get {
                return ResourceManager.GetString("heading_dialog_select_payer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Room.
        /// </summary>
        public static string heading_dialog_select_room {
            get {
                return ResourceManager.GetString("heading_dialog_select_room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string heading_dialog_summary {
            get {
                return ResourceManager.GetString("heading_dialog_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date:.
        /// </summary>
        public static string heading_end_day_2 {
            get {
                return ResourceManager.GetString("heading_end_day_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Guest Details:.
        /// </summary>
        public static string heading_enter_guest_details {
            get {
                return ResourceManager.GetString("heading_enter_guest_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Host Server:.
        /// </summary>
        public static string heading_select_a_host_server {
            get {
                return ResourceManager.GetString("heading_select_a_host_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Database:.
        /// </summary>
        public static string heading_select_database {
            get {
                return ResourceManager.GetString("heading_select_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Room:.
        /// </summary>
        public static string heading_select_room_2 {
            get {
                return ResourceManager.GetString("heading_select_room_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string heading_server {
            get {
                return ResourceManager.GetString("heading_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string heading_sign_in {
            get {
                return ResourceManager.GetString("heading_sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date:.
        /// </summary>
        public static string heading_start_day_2 {
            get {
                return ResourceManager.GetString("heading_start_day_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Other Servers.
        /// </summary>
        public static string heading_your_other_servers {
            get {
                return ResourceManager.GetString("heading_your_other_servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string hint_amount {
            get {
                return ResourceManager.GetString("hint_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string hint_database {
            get {
                return ResourceManager.GetString("hint_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount (Optional).
        /// </summary>
        public static string hint_discount_optional {
            get {
                return ResourceManager.GetString("hint_discount_optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Number.
        /// </summary>
        public static string hint_document_number {
            get {
                return ResourceManager.GetString("hint_document_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string hint_email {
            get {
                return ResourceManager.GetString("hint_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string hint_full_name {
            get {
                return ResourceManager.GetString("hint_full_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string hint_mobile_number {
            get {
                return ResourceManager.GetString("hint_mobile_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport/ID.
        /// </summary>
        public static string hint_passport_id {
            get {
                return ResourceManager.GetString("hint_passport_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string hint_password {
            get {
                return ResourceManager.GetString("hint_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string hint_phone_number {
            get {
                return ResourceManager.GetString("hint_phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Country.
        /// </summary>
        public static string hint_search_country {
            get {
                return ResourceManager.GetString("hint_search_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Guest Name.
        /// </summary>
        public static string hint_search_guest_name {
            get {
                return ResourceManager.GetString("hint_search_guest_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Item Name.
        /// </summary>
        public static string hint_search_item_name {
            get {
                return ResourceManager.GetString("hint_search_item_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Property.
        /// </summary>
        public static string hint_search_property {
            get {
                return ResourceManager.GetString("hint_search_property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Room Name.
        /// </summary>
        public static string hint_search_room_name {
            get {
                return ResourceManager.GetString("hint_search_room_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server URL.
        /// </summary>
        public static string hint_server_url {
            get {
                return ResourceManager.GetString("hint_server_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string hint_username {
            get {
                return ResourceManager.GetString("hint_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Booking.
        /// </summary>
        public static string image_text_add_booking {
            get {
                return ResourceManager.GetString("image_text_add_booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check In.
        /// </summary>
        public static string image_text_check_in {
            get {
                return ResourceManager.GetString("image_text_check_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Bookings.
        /// </summary>
        public static string image_text_open_bookings {
            get {
                return ResourceManager.GetString("image_text_open_bookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string image_text_statistics {
            get {
                return ResourceManager.GetString("image_text_statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close navigation drawer.
        /// </summary>
        public static string navigation_drawer_close {
            get {
                return ResourceManager.GetString("navigation_drawer_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open navigation drawer.
        /// </summary>
        public static string navigation_drawer_open {
            get {
                return ResourceManager.GetString("navigation_drawer_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Database found.
        /// </summary>
        public static string no_database_found {
            get {
                return ResourceManager.GetString("no_database_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string page_title_my_profile {
            get {
                return ResourceManager.GetString("page_title_my_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Map.
        /// </summary>
        public static string page_title_pick_map {
            get {
                return ResourceManager.GetString("page_title_pick_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log into your Kamooni System.
        /// </summary>
        public static string qr_content_1_TextView {
            get {
                return ResourceManager.GetString("qr_content_1_TextView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Bookings.
        /// </summary>
        public static string qr_content_2_TextView {
            get {
                return ResourceManager.GetString("qr_content_2_TextView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Settings &gt; Property Details.
        /// </summary>
        public static string qr_content_3_TextView {
            get {
                return ResourceManager.GetString("qr_content_3_TextView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under the Kamooni tab.
        /// </summary>
        public static string qr_content_4_TextView {
            get {
                return ResourceManager.GetString("qr_content_4_TextView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan the QR Code.
        /// </summary>
        public static string qr_content_5_TextView {
            get {
                return ResourceManager.GetString("qr_content_5_TextView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Database.
        /// </summary>
        public static string select_database {
            get {
                return ResourceManager.GetString("select_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server not found.
        /// </summary>
        public static string server_not_found {
            get {
                return ResourceManager.GetString("server_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string subheading_amount {
            get {
                return ResourceManager.GetString("subheading_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount:.
        /// </summary>
        public static string subheading_amount_2 {
            get {
                return ResourceManager.GetString("subheading_amount_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string subheading_balance {
            get {
                return ResourceManager.GetString("subheading_balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance:.
        /// </summary>
        public static string subheading_balance_2 {
            get {
                return ResourceManager.GetString("subheading_balance_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Details:.
        /// </summary>
        public static string subheading_bank {
            get {
                return ResourceManager.GetString("subheading_bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Ref.
        /// </summary>
        public static string subheading_booking_ref {
            get {
                return ResourceManager.GetString("subheading_booking_ref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string subheading_date {
            get {
                return ResourceManager.GetString("subheading_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string subheading_discount {
            get {
                return ResourceManager.GetString("subheading_discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount:.
        /// </summary>
        public static string subheading_discount_2 {
            get {
                return ResourceManager.GetString("subheading_discount_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string subheading_guest {
            get {
                return ResourceManager.GetString("subheading_guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Name.
        /// </summary>
        public static string subheading_guest_name {
            get {
                return ResourceManager.GetString("subheading_guest_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Name:.
        /// </summary>
        public static string subheading_guest_name_2 {
            get {
                return ResourceManager.GetString("subheading_guest_name_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        public static string subheading_item_name {
            get {
                return ResourceManager.GetString("subheading_item_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo:.
        /// </summary>
        public static string subheading_logo {
            get {
                return ResourceManager.GetString("subheading_logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        public static string subheading_method {
            get {
                return ResourceManager.GetString("subheading_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number:.
        /// </summary>
        public static string subheading_mobile {
            get {
                return ResourceManager.GetString("subheading_mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nights.
        /// </summary>
        public static string subheading_nights {
            get {
                return ResourceManager.GetString("subheading_nights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Guests:.
        /// </summary>
        public static string subheading_no_of_guests {
            get {
                return ResourceManager.GetString("subheading_no_of_guests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Adults.
        /// </summary>
        public static string subheading_number_of_adults {
            get {
                return ResourceManager.GetString("subheading_number_of_adults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string subheading_paid {
            get {
                return ResourceManager.GetString("subheading_paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Details.
        /// </summary>
        public static string subheading_passport_details {
            get {
                return ResourceManager.GetString("subheading_passport_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payer:.
        /// </summary>
        public static string subheading_payer {
            get {
                return ResourceManager.GetString("subheading_payer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method:.
        /// </summary>
        public static string subheading_payment_method {
            get {
                return ResourceManager.GetString("subheading_payment_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string subheading_price {
            get {
                return ResourceManager.GetString("subheading_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To access your property:.
        /// </summary>
        public static string subheading_qr_TextView {
            get {
                return ResourceManager.GetString("subheading_qr_TextView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string subheading_quantity {
            get {
                return ResourceManager.GetString("subheading_quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        public static string subheading_room {
            get {
                return ResourceManager.GetString("subheading_room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Name.
        /// </summary>
        public static string subheading_room_name {
            get {
                return ResourceManager.GetString("subheading_room_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Type Capacity:.
        /// </summary>
        public static string subheading_room_type_capacity {
            get {
                return ResourceManager.GetString("subheading_room_type_capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select:.
        /// </summary>
        public static string subheading_select {
            get {
                return ResourceManager.GetString("subheading_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Customer.
        /// </summary>
        public static string subheading_select_customer {
            get {
                return ResourceManager.GetString("subheading_select_customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleeps.
        /// </summary>
        public static string subheading_sleeps {
            get {
                return ResourceManager.GetString("subheading_sleeps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxes.
        /// </summary>
        public static string subheading_taxes {
            get {
                return ResourceManager.GetString("subheading_taxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string subheading_total {
            get {
                return ResourceManager.GetString("subheading_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        public static string subheading_total_2 {
            get {
                return ResourceManager.GetString("subheading_total_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string subheading_type {
            get {
                return ResourceManager.GetString("subheading_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string subheading_unit_price {
            get {
                return ResourceManager.GetString("subheading_unit_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units Left.
        /// </summary>
        public static string subheading_units_left {
            get {
                return ResourceManager.GetString("subheading_units_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Server.
        /// </summary>
        public static string title_activity_add_server {
            get {
                return ResourceManager.GetString("title_activity_add_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Dates.
        /// </summary>
        public static string title_activity_booking_calendar {
            get {
                return ResourceManager.GetString("title_activity_booking_calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Details.
        /// </summary>
        public static string title_activity_booking_customer {
            get {
                return ResourceManager.GetString("title_activity_booking_customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Rooms.
        /// </summary>
        public static string title_activity_booking_room {
            get {
                return ResourceManager.GetString("title_activity_booking_room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookings.
        /// </summary>
        public static string title_activity_bookings {
            get {
                return ResourceManager.GetString("title_activity_bookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrivals.
        /// </summary>
        public static string title_activity_check_in {
            get {
                return ResourceManager.GetString("title_activity_check_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bills.
        /// </summary>
        public static string title_activity_checked_in_booking_detail {
            get {
                return ResourceManager.GetString("title_activity_checked_in_booking_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check outs for Today.
        /// </summary>
        public static string title_activity_checked_out {
            get {
                return ResourceManager.GetString("title_activity_checked_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string title_activity_create_host {
            get {
                return ResourceManager.GetString("title_activity_create_host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string title_activity_extra_summary {
            get {
                return ResourceManager.GetString("title_activity_extra_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string title_activity_guest {
            get {
                return ResourceManager.GetString("title_activity_guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Book.
        /// </summary>
        public static string title_activity_guest_book {
            get {
                return ResourceManager.GetString("title_activity_guest_book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Details.
        /// </summary>
        public static string title_activity_guest_details {
            get {
                return ResourceManager.GetString("title_activity_guest_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Profile.
        /// </summary>
        public static string title_activity_guest_profile {
            get {
                return ResourceManager.GetString("title_activity_guest_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Your Property.
        /// </summary>
        public static string title_activity_host_directory {
            get {
                return ResourceManager.GetString("title_activity_host_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string title_activity_log_in {
            get {
                return ResourceManager.GetString("title_activity_log_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Servers.
        /// </summary>
        public static string title_activity_manage_servers {
            get {
                return ResourceManager.GetString("title_activity_manage_servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Now.
        /// </summary>
        public static string title_activity_pay_now {
            get {
                return ResourceManager.GetString("title_activity_pay_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Guest.
        /// </summary>
        public static string title_activity_select_guest {
            get {
                return ResourceManager.GetString("title_activity_select_guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string title_activity_settings {
            get {
                return ResourceManager.GetString("title_activity_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string title_activity_sign_in_description {
            get {
                return ResourceManager.GetString("title_activity_sign_in_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string title_activity_stats {
            get {
                return ResourceManager.GetString("title_activity_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        public static string title_activity_terms_conditions {
            get {
                return ResourceManager.GetString("title_activity_terms_conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bills.
        /// </summary>
        public static string title_activity_view_bills {
            get {
                return ResourceManager.GetString("title_activity_view_bills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string title_popup_close {
            get {
                return ResourceManager.GetString("title_popup_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Payment.
        /// </summary>
        public static string title_popup_register_payment {
            get {
                return ResourceManager.GetString("title_popup_register_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT NATIONALITY.
        /// </summary>
        public static string title_popup_select_nationality {
            get {
                return ResourceManager.GetString("title_popup_select_nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ROOM.
        /// </summary>
        public static string title_popup_select_room {
            get {
                return ResourceManager.GetString("title_popup_select_room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Early.
        /// </summary>
        public static string title_tab_early_arrivals {
            get {
                return ResourceManager.GetString("title_tab_early_arrivals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No-Shows.
        /// </summary>
        public static string title_tab_no_shows {
            get {
                return ResourceManager.GetString("title_tab_no_shows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string title_tab_today {
            get {
                return ResourceManager.GetString("title_tab_today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
